// <auto-generated />
using System;
using FantasyLeague.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FantasyLeague.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260806102441_AddRoleColumnForUser")]
    partial class AddRoleColumnForUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FantasyLeague.Domain.Entities.Auth.RefreshToken", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Token");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("FantasyLeague.Domain.Entities.Drafts.DraftPickOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("NbaPlayerId")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<int>("OverallPick")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PickedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PositionInRound")
                        .HasColumnType("integer");

                    b.Property<int>("Round")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NbaPlayerId");

                    b.HasIndex("LeagueId", "NbaPlayerId")
                        .IsUnique()
                        .HasFilter("\"NbaPlayerId\" IS NOT NULL");

                    b.HasIndex("LeagueId", "OverallPick")
                        .IsUnique();

                    b.HasIndex("TeamId", "LeagueId");

                    b.HasIndex("LeagueId", "Round", "PositionInRound")
                        .IsUnique();

                    b.ToTable("draft_pick_orders", (string)null);
                });

            modelBuilder.Entity("FantasyLeague.Domain.Entities.FantasyTeams.FantasyTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("LeagueId", "Name")
                        .IsUnique();

                    b.HasIndex("LeagueId", "OwnerId")
                        .IsUnique();

                    b.ToTable("fantasy_teams", (string)null);
                });

            modelBuilder.Entity("FantasyLeague.Domain.Entities.FantasyTeams.FantasyTeamPlayer", b =>
                {
                    b.Property<Guid>("FantasyTeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NbaPlayerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.HasKey("FantasyTeamId", "NbaPlayerId");

                    b.HasIndex("NbaPlayerId");

                    b.HasIndex("FantasyTeamId", "LeagueId");

                    b.HasIndex("LeagueId", "NbaPlayerId")
                        .IsUnique();

                    b.ToTable("fantasy_team_players", (string)null);
                });

            modelBuilder.Entity("FantasyLeague.Domain.Entities.Leagues.League", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommissionerId")
                        .HasColumnType("uuid");

                    b.Property<int>("ConsecutiveDraftFailureCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int>("MaxTeams")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CommissionerId");

                    b.HasIndex("JoinCode")
                        .IsUnique();

                    b.ToTable("leagues", (string)null);
                });

            modelBuilder.Entity("FantasyLeague.Domain.Entities.Leagues.LeagueFixture", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("AwayScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("GameTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("Week")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId", "LeagueId");

                    b.HasIndex("HomeTeamId", "LeagueId");

                    b.HasIndex("LeagueId", "Week");

                    b.HasIndex("LeagueId", "HomeTeamId", "AwayTeamId")
                        .IsUnique();

                    b.ToTable("league_fixtures", (string)null);
                });

            modelBuilder.Entity("FantasyLeague.Domain.Entities.Leagues.LeagueSettings", b =>
                {
                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DraftDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DraftTimeZoneId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("UTC");

                    b.Property<int>("RosterSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(13);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LeagueId");

                    b.ToTable("league_settings", (string)null);
                });

            modelBuilder.Entity("FantasyLeague.Domain.Entities.Players.NbaPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("HeightCm")
                        .HasColumnType("integer");

                    b.Property<int?>("JerseyNumber")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NbaId")
                        .HasColumnType("integer");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.Property<string>("Team")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("FirstName");

                    b.HasIndex("LastName");

                    b.HasIndex("NbaId")
                        .IsUnique();

                    b.ToTable("nba_players", (string)null);
                });

            modelBuilder.Entity("FantasyLeague.Domain.Entities.Players.PlayerStats", b =>
                {
                    b.Property<Guid>("NbaPlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<double>("AssistsPerGame")
                        .HasColumnType("double precision");

                    b.Property<double>("BlocksPerGame")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("FieldGoalPercentage")
                        .HasColumnType("double precision");

                    b.Property<double>("FreeThrowPercentage")
                        .HasColumnType("double precision");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("GamesStarted")
                        .HasColumnType("integer");

                    b.Property<double>("MinutesPerGame")
                        .HasColumnType("double precision");

                    b.Property<double>("PointsPerGame")
                        .HasColumnType("double precision");

                    b.Property<double>("ReboundsPerGame")
                        .HasColumnType("double precision");

                    b.Property<double>("StealsPerGame")
                        .HasColumnType("double precision");

                    b.Property<double>("ThreePointPercentage")
                        .HasColumnType("double precision");

                    b.Property<double>("TurnoversPerGame")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("NbaPlayerId", "Season");

                    b.ToTable("player_stats", (string)null);
                });

            modelBuilder.Entity("FantasyLeague.Domain.Entities.Transfers.TransferRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CounterpartyTeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InitiatingTeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.ToTable("transfer_requests", (string)null);
                });

            modelBuilder.Entity("FantasyLeague.Domain.Entities.Transfers.TransferRequestPlayer", b =>
                {
                    b.Property<Guid>("TransferRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FromTeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NbaPlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("TransferRequestId", "FromTeamId", "NbaPlayerId");

                    b.ToTable("transfer_request_players", (string)null);
                });

            modelBuilder.Entity("FantasyLeague.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("UTC");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("FantasyLeague.Domain.Entities.Drafts.DraftPickOrder", b =>
                {
                    b.HasOne("FantasyLeague.Domain.Entities.Leagues.League", null)
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyLeague.Domain.Entities.Players.NbaPlayer", null)
                        .WithMany()
                        .HasForeignKey("NbaPlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FantasyLeague.Domain.Entities.FantasyTeams.FantasyTeam", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "LeagueId")
                        .HasPrincipalKey("Id", "LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyLeague.Domain.Entities.FantasyTeams.FantasyTeam", b =>
                {
                    b.HasOne("FantasyLeague.Domain.Entities.Leagues.League", null)
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyLeague.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyLeague.Domain.Entities.FantasyTeams.FantasyTeamPlayer", b =>
                {
                    b.HasOne("FantasyLeague.Domain.Entities.Players.NbaPlayer", null)
                        .WithMany()
                        .HasForeignKey("NbaPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FantasyLeague.Domain.Entities.FantasyTeams.FantasyTeam", null)
                        .WithMany("Players")
                        .HasForeignKey("FantasyTeamId", "LeagueId")
                        .HasPrincipalKey("Id", "LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyLeague.Domain.Entities.Leagues.League", b =>
                {
                    b.HasOne("FantasyLeague.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CommissionerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyLeague.Domain.Entities.Leagues.LeagueFixture", b =>
                {
                    b.HasOne("FantasyLeague.Domain.Entities.Leagues.League", null)
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyLeague.Domain.Entities.FantasyTeams.FantasyTeam", null)
                        .WithMany()
                        .HasForeignKey("AwayTeamId", "LeagueId")
                        .HasPrincipalKey("Id", "LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FantasyLeague.Domain.Entities.FantasyTeams.FantasyTeam", null)
                        .WithMany()
                        .HasForeignKey("HomeTeamId", "LeagueId")
                        .HasPrincipalKey("Id", "LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyLeague.Domain.Entities.Leagues.LeagueSettings", b =>
                {
                    b.HasOne("FantasyLeague.Domain.Entities.Leagues.League", null)
                        .WithOne("Settings")
                        .HasForeignKey("FantasyLeague.Domain.Entities.Leagues.LeagueSettings", "LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyLeague.Domain.Entities.Players.PlayerStats", b =>
                {
                    b.HasOne("FantasyLeague.Domain.Entities.Players.NbaPlayer", null)
                        .WithMany("SeasonStats")
                        .HasForeignKey("NbaPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyLeague.Domain.Entities.Transfers.TransferRequestPlayer", b =>
                {
                    b.HasOne("FantasyLeague.Domain.Entities.Transfers.TransferRequest", null)
                        .WithMany("Players")
                        .HasForeignKey("TransferRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyLeague.Domain.Entities.FantasyTeams.FantasyTeam", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("FantasyLeague.Domain.Entities.Leagues.League", b =>
                {
                    b.Navigation("Settings")
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyLeague.Domain.Entities.Players.NbaPlayer", b =>
                {
                    b.Navigation("SeasonStats");
                });

            modelBuilder.Entity("FantasyLeague.Domain.Entities.Transfers.TransferRequest", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
