@FantasyLeague.WebApi_HostAddress = http://localhost:5129

GET {{FantasyLeague.WebApi_HostAddress}}/health
Accept: application/json

###

POST {{FantasyLeague.WebApi_HostAddress}}/api/nba-players/sync
Accept: application/json

###
