// <auto-generated />
using System;
using FantasyLeague.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FantasyLeague.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260718180522_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FantasyLeague.Domain.Entities.NbaPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("HeightCm")
                        .HasColumnType("integer");

                    b.Property<int?>("JerseyNumber")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NbaId")
                        .HasColumnType("integer");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.Property<string>("Team")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("nba_players", (string)null);
                });

            modelBuilder.Entity("FantasyLeague.Domain.Entities.PlayerStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AssistsPerGame")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BlocksPerGame")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FieldGoalPercentage")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FreeThrowPercentage")
                        .HasColumnType("numeric");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("GamesStarted")
                        .HasColumnType("integer");

                    b.Property<decimal>("MinutesPerGame")
                        .HasColumnType("numeric");

                    b.Property<Guid>("NbaPlayerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PointsPerGame")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ReboundsPerGame")
                        .HasColumnType("numeric");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<decimal>("StealsPerGame")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ThreePointPercentage")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TurnoversPerGame")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NbaPlayerId");

                    b.ToTable("player_stats", (string)null);
                });

            modelBuilder.Entity("FantasyLeague.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("FantasyLeague.Domain.Entities.PlayerStats", b =>
                {
                    b.HasOne("FantasyLeague.Domain.Entities.NbaPlayer", "NbaPlayer")
                        .WithMany("SeasonStats")
                        .HasForeignKey("NbaPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NbaPlayer");
                });

            modelBuilder.Entity("FantasyLeague.Domain.Entities.NbaPlayer", b =>
                {
                    b.Navigation("SeasonStats");
                });
#pragma warning restore 612, 618
        }
    }
}
